/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LpOnlineMbaRouteImport } from './routes/lp-online-mba'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProgramsOnlineMbaRouteImport } from './routes/programs/online-mba'
import { Route as ProgramsOnlineDiplomaRouteImport } from './routes/programs/online-diploma'
import { Route as ProgramsOnlineCertificateRouteImport } from './routes/programs/online-certificate'
import { Route as ProgramsOnlineBcomRouteImport } from './routes/programs/online-bcom'
import { Route as ProgramsOnlineBbaRouteImport } from './routes/programs/online-bba'
import { Route as BlogNmimsOnlineMbaFeesEmiGuideRouteImport } from './routes/blog/nmims-online-mba-fees-emi-guide'
import { Route as BlogIsOnlineMbaValidUgcEquivalenceRouteImport } from './routes/blog/is-online-mba-valid-ugc-equivalence'
import { Route as BlogAbcIdDebIdGuideNmimsCdoeRouteImport } from './routes/blog/abc-id-deb-id-guide-nmims-cdoe'

const LpOnlineMbaRoute = LpOnlineMbaRouteImport.update({
  id: '/lp-online-mba',
  path: '/lp-online-mba',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOnlineMbaRoute = ProgramsOnlineMbaRouteImport.update({
  id: '/programs/online-mba',
  path: '/programs/online-mba',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOnlineDiplomaRoute = ProgramsOnlineDiplomaRouteImport.update({
  id: '/programs/online-diploma',
  path: '/programs/online-diploma',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOnlineCertificateRoute =
  ProgramsOnlineCertificateRouteImport.update({
    id: '/programs/online-certificate',
    path: '/programs/online-certificate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsOnlineBcomRoute = ProgramsOnlineBcomRouteImport.update({
  id: '/programs/online-bcom',
  path: '/programs/online-bcom',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsOnlineBbaRoute = ProgramsOnlineBbaRouteImport.update({
  id: '/programs/online-bba',
  path: '/programs/online-bba',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNmimsOnlineMbaFeesEmiGuideRoute =
  BlogNmimsOnlineMbaFeesEmiGuideRouteImport.update({
    id: '/blog/nmims-online-mba-fees-emi-guide',
    path: '/blog/nmims-online-mba-fees-emi-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIsOnlineMbaValidUgcEquivalenceRoute =
  BlogIsOnlineMbaValidUgcEquivalenceRouteImport.update({
    id: '/blog/is-online-mba-valid-ugc-equivalence',
    path: '/blog/is-online-mba-valid-ugc-equivalence',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAbcIdDebIdGuideNmimsCdoeRoute =
  BlogAbcIdDebIdGuideNmimsCdoeRouteImport.update({
    id: '/blog/abc-id-deb-id-guide-nmims-cdoe',
    path: '/blog/abc-id-deb-id-guide-nmims-cdoe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/lp-online-mba': typeof LpOnlineMbaRoute
  '/blog/abc-id-deb-id-guide-nmims-cdoe': typeof BlogAbcIdDebIdGuideNmimsCdoeRoute
  '/blog/is-online-mba-valid-ugc-equivalence': typeof BlogIsOnlineMbaValidUgcEquivalenceRoute
  '/blog/nmims-online-mba-fees-emi-guide': typeof BlogNmimsOnlineMbaFeesEmiGuideRoute
  '/programs/online-bba': typeof ProgramsOnlineBbaRoute
  '/programs/online-bcom': typeof ProgramsOnlineBcomRoute
  '/programs/online-certificate': typeof ProgramsOnlineCertificateRoute
  '/programs/online-diploma': typeof ProgramsOnlineDiplomaRoute
  '/programs/online-mba': typeof ProgramsOnlineMbaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/lp-online-mba': typeof LpOnlineMbaRoute
  '/blog/abc-id-deb-id-guide-nmims-cdoe': typeof BlogAbcIdDebIdGuideNmimsCdoeRoute
  '/blog/is-online-mba-valid-ugc-equivalence': typeof BlogIsOnlineMbaValidUgcEquivalenceRoute
  '/blog/nmims-online-mba-fees-emi-guide': typeof BlogNmimsOnlineMbaFeesEmiGuideRoute
  '/programs/online-bba': typeof ProgramsOnlineBbaRoute
  '/programs/online-bcom': typeof ProgramsOnlineBcomRoute
  '/programs/online-certificate': typeof ProgramsOnlineCertificateRoute
  '/programs/online-diploma': typeof ProgramsOnlineDiplomaRoute
  '/programs/online-mba': typeof ProgramsOnlineMbaRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/lp-online-mba': typeof LpOnlineMbaRoute
  '/blog/abc-id-deb-id-guide-nmims-cdoe': typeof BlogAbcIdDebIdGuideNmimsCdoeRoute
  '/blog/is-online-mba-valid-ugc-equivalence': typeof BlogIsOnlineMbaValidUgcEquivalenceRoute
  '/blog/nmims-online-mba-fees-emi-guide': typeof BlogNmimsOnlineMbaFeesEmiGuideRoute
  '/programs/online-bba': typeof ProgramsOnlineBbaRoute
  '/programs/online-bcom': typeof ProgramsOnlineBcomRoute
  '/programs/online-certificate': typeof ProgramsOnlineCertificateRoute
  '/programs/online-diploma': typeof ProgramsOnlineDiplomaRoute
  '/programs/online-mba': typeof ProgramsOnlineMbaRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/lp-online-mba'
    | '/blog/abc-id-deb-id-guide-nmims-cdoe'
    | '/blog/is-online-mba-valid-ugc-equivalence'
    | '/blog/nmims-online-mba-fees-emi-guide'
    | '/programs/online-bba'
    | '/programs/online-bcom'
    | '/programs/online-certificate'
    | '/programs/online-diploma'
    | '/programs/online-mba'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/lp-online-mba'
    | '/blog/abc-id-deb-id-guide-nmims-cdoe'
    | '/blog/is-online-mba-valid-ugc-equivalence'
    | '/blog/nmims-online-mba-fees-emi-guide'
    | '/programs/online-bba'
    | '/programs/online-bcom'
    | '/programs/online-certificate'
    | '/programs/online-diploma'
    | '/programs/online-mba'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/lp-online-mba'
    | '/blog/abc-id-deb-id-guide-nmims-cdoe'
    | '/blog/is-online-mba-valid-ugc-equivalence'
    | '/blog/nmims-online-mba-fees-emi-guide'
    | '/programs/online-bba'
    | '/programs/online-bcom'
    | '/programs/online-certificate'
    | '/programs/online-diploma'
    | '/programs/online-mba'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  LpOnlineMbaRoute: typeof LpOnlineMbaRoute
  BlogAbcIdDebIdGuideNmimsCdoeRoute: typeof BlogAbcIdDebIdGuideNmimsCdoeRoute
  BlogIsOnlineMbaValidUgcEquivalenceRoute: typeof BlogIsOnlineMbaValidUgcEquivalenceRoute
  BlogNmimsOnlineMbaFeesEmiGuideRoute: typeof BlogNmimsOnlineMbaFeesEmiGuideRoute
  ProgramsOnlineBbaRoute: typeof ProgramsOnlineBbaRoute
  ProgramsOnlineBcomRoute: typeof ProgramsOnlineBcomRoute
  ProgramsOnlineCertificateRoute: typeof ProgramsOnlineCertificateRoute
  ProgramsOnlineDiplomaRoute: typeof ProgramsOnlineDiplomaRoute
  ProgramsOnlineMbaRoute: typeof ProgramsOnlineMbaRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lp-online-mba': {
      id: '/lp-online-mba'
      path: '/lp-online-mba'
      fullPath: '/lp-online-mba'
      preLoaderRoute: typeof LpOnlineMbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/online-mba': {
      id: '/programs/online-mba'
      path: '/programs/online-mba'
      fullPath: '/programs/online-mba'
      preLoaderRoute: typeof ProgramsOnlineMbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/online-diploma': {
      id: '/programs/online-diploma'
      path: '/programs/online-diploma'
      fullPath: '/programs/online-diploma'
      preLoaderRoute: typeof ProgramsOnlineDiplomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/online-certificate': {
      id: '/programs/online-certificate'
      path: '/programs/online-certificate'
      fullPath: '/programs/online-certificate'
      preLoaderRoute: typeof ProgramsOnlineCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/online-bcom': {
      id: '/programs/online-bcom'
      path: '/programs/online-bcom'
      fullPath: '/programs/online-bcom'
      preLoaderRoute: typeof ProgramsOnlineBcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/online-bba': {
      id: '/programs/online-bba'
      path: '/programs/online-bba'
      fullPath: '/programs/online-bba'
      preLoaderRoute: typeof ProgramsOnlineBbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/nmims-online-mba-fees-emi-guide': {
      id: '/blog/nmims-online-mba-fees-emi-guide'
      path: '/blog/nmims-online-mba-fees-emi-guide'
      fullPath: '/blog/nmims-online-mba-fees-emi-guide'
      preLoaderRoute: typeof BlogNmimsOnlineMbaFeesEmiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/is-online-mba-valid-ugc-equivalence': {
      id: '/blog/is-online-mba-valid-ugc-equivalence'
      path: '/blog/is-online-mba-valid-ugc-equivalence'
      fullPath: '/blog/is-online-mba-valid-ugc-equivalence'
      preLoaderRoute: typeof BlogIsOnlineMbaValidUgcEquivalenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/abc-id-deb-id-guide-nmims-cdoe': {
      id: '/blog/abc-id-deb-id-guide-nmims-cdoe'
      path: '/blog/abc-id-deb-id-guide-nmims-cdoe'
      fullPath: '/blog/abc-id-deb-id-guide-nmims-cdoe'
      preLoaderRoute: typeof BlogAbcIdDebIdGuideNmimsCdoeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  LpOnlineMbaRoute: LpOnlineMbaRoute,
  BlogAbcIdDebIdGuideNmimsCdoeRoute: BlogAbcIdDebIdGuideNmimsCdoeRoute,
  BlogIsOnlineMbaValidUgcEquivalenceRoute:
    BlogIsOnlineMbaValidUgcEquivalenceRoute,
  BlogNmimsOnlineMbaFeesEmiGuideRoute: BlogNmimsOnlineMbaFeesEmiGuideRoute,
  ProgramsOnlineBbaRoute: ProgramsOnlineBbaRoute,
  ProgramsOnlineBcomRoute: ProgramsOnlineBcomRoute,
  ProgramsOnlineCertificateRoute: ProgramsOnlineCertificateRoute,
  ProgramsOnlineDiplomaRoute: ProgramsOnlineDiplomaRoute,
  ProgramsOnlineMbaRoute: ProgramsOnlineMbaRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
