import { createFileRoute } from "@tanstack/react-router";

// Styles the sitemap index into a readable table when opened in a browser —
// search engines ignore this entirely and just parse the underlying XML.
const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
<title>XML Sitemap</title>
<style>
  body { font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: rgb(84, 83, 83); margin: 30px; background: #fff; }
  #sitemap { max-width: 990px; margin: 0 auto; }
  h1 { font-size: 30px; font-weight: 700; color: #333; margin: 0 0 16px; }
  p { margin: 0 0 8px; line-height: 16px; }
  a.brand { color: #b3382c; font-weight: 700; text-decoration: none; }
  a.brand:hover { text-decoration: underline; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: inherit; font-family: inherit; }
  th { text-align: left; padding: 0 8px 6px 0; border-bottom: 1px solid #333; font-weight: 700; color: #333; }
  td { padding: 8px 8px 8px 0; }
  tr:nth-child(even) td { background: #f0f0f0; }
  td a { color: rgb(84, 83, 83); text-decoration: none; }
  td a:hover { text-decoration: underline; }
</style>
</head>
<body>
<div id="sitemap">
<h1>XML Sitemap</h1>
<p>Generated by <a class="brand" href="/">cdoe.info</a>, this is an XML Sitemap, meant for consumption by search engines.</p>
<p>You can find more information about XML sitemaps on <a class="brand" href="https://www.sitemaps.org/" target="_blank" rel="noopener">sitemaps.org</a>.</p>
<p>This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.</p>
<table>
<tr><th>Sitemap</th><th>Last Modified</th></tr>
<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
<tr>
<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="concat(substring(sitemap:lastmod,1,10),' ',substring(sitemap:lastmod,12,5),' +00:00')"/></td>
</tr>
</xsl:for-each>
</table>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
`;

export const Route = createFileRoute("/main-sitemap.xsl")({
  server: {
    handlers: {
      GET: async () =>
        new Response(XSL, {
          headers: {
            "Content-Type": "application/xslt+xml; charset=utf-8",
            "Cache-Control": "no-cache, must-revalidate",
          },
        }),
    },
  },
});
