import { createFileRoute } from "@tanstack/react-router";

// Styles page-sitemap.xml / post-sitemap.xml into a readable table when
// opened in a browser — search engines ignore this and just parse the XML.
const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
<title>XML Sitemap</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 14px; color: #222; margin: 24px; background: #fff; }
  #sitemap { max-width: 980px; margin: 0 auto; }
  h1 { font-size: 26px; font-weight: 700; margin: 0 0 18px; }
  p { margin: 0 0 8px; }
  a.brand { color: #b3382c; font-weight: 700; text-decoration: none; }
  a.brand:hover { text-decoration: underline; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th { text-align: left; padding: 9px 10px; border-bottom: 1px solid #ccc; font-weight: 700; }
  td { padding: 7px 10px; }
  tr:nth-child(even) td { background: #f0f0f0; }
  td a { color: #999; text-decoration: none; }
  td a:hover { text-decoration: underline; }
</style>
</head>
<body>
<div id="sitemap">
<h1>XML Sitemap</h1>
<p>Generated by <a class="brand" href="/">cdoe.info</a>, this is an XML Sitemap, meant for consumption by search engines.</p>
<p>You can find more information about XML sitemaps on <a class="brand" href="https://www.sitemaps.org/" target="_blank" rel="noopener">sitemaps.org</a>.</p>
<p>This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
<table>
<tr><th>URL</th><th>Images</th><th>Last Mod.</th></tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="count(image:image)"/></td>
<td><xsl:value-of select="concat(substring(sitemap:lastmod,1,10),' ',substring(sitemap:lastmod,12,5),' +00:00')"/></td>
</tr>
</xsl:for-each>
</table>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
`;

export const Route = createFileRoute("/sitemap.xsl")({
  server: {
    handlers: {
      GET: async () =>
        new Response(XSL, {
          headers: { "Content-Type": "application/xslt+xml; charset=utf-8" },
        }),
    },
  },
});
